# Generated by Django 5.1.6 on 2025-04-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(),
        ),
    ]
